binning: {binsz: 0.005, coordsys: CEL, enumbins: 20, nxpix: 500, nypix: 500, proj: TAN}
logging: {working_dir: .}
model: {alphapar: 2.47, beta: 0.10423, dec: 22.0144, pivot_energy: 1, prefactor: 3.23e-11,
  ra: 83.6333, rad: 0.1, source: "\u2019Nebula\u2019", spectrum: LogParabola, template: Sphere2D,
  use_psf: false}
pointing: {dec: 22.0144, livetime: 50.0 hour, ra: 83.6333}
selection: {ROI: 5 deg, emax: 300.0, emin: 0.02, offset_fov: 2}
